IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'PrinterType') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD PrinterType NVARCHAR(50) NOT NULL DEFAULT 'Thermal';
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'Language') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD Language NVARCHAR(20) NOT NULL DEFAULT 'TSPL'; -- TSPL | ZPL | EPL | WINDOWS | PDF
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'MinDensity') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD MinDensity INT NOT NULL DEFAULT 1;
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'MaxDensity') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD MaxDensity INT NOT NULL DEFAULT 15;
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'MinSpeed') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD MinSpeed INT NOT NULL DEFAULT 1;
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'MaxSpeed') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD MaxSpeed INT NOT NULL DEFAULT 4;
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'SupportsGap') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD SupportsGap BIT NOT NULL DEFAULT 1;
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'SupportsOffset') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD SupportsOffset BIT NOT NULL DEFAULT 1;
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'GapMm') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD GapMm DECIMAL(10,2) NOT NULL DEFAULT 3;
GO

IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'OffsetMm') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD OffsetMm DECIMAL(10,2) NOT NULL DEFAULT 0;
GO

-- Drives every mm-to-dot conversion in the generated printer command (printerCommandService.mmToDots)
-- — this printer family is 203 DPI; a 300 DPI printer needs this set explicitly on its own row.
IF COL_LENGTH('dbo.T_LABEL_PRINT_CONFIG', 'DPI') IS NULL
    ALTER TABLE dbo.T_LABEL_PRINT_CONFIG ADD DPI INT NOT NULL DEFAULT 203;
GO

UPDATE dbo.T_LABEL_PRINT_CONFIG
SET PrinterType = 'Thermal', Language = 'TSPL', MinDensity = 1, MaxDensity = 15, MinSpeed = 1, MaxSpeed = 4,
    SupportsGap = 1, SupportsOffset = 1, GapMm = 3, OffsetMm = 0, DPI = 203
WHERE PrinterName = 'TSC TTP-244 Pro' AND MinDensity = 1 AND MaxDensity = 15 AND Language = 'TSPL';
GO
